import { fetchCharacter } from '../../../lib/api';
import { Character } from '../../../lib/types';
import LoadingSpinner from '../../../components/LoadingSpinner';
import ErrorMessage from '../../../components/ErrorMessage';

interface PageProps {
  params: Promise<{
    id: string;
  }>;
}

export default async function CharacterDetail({ params }: PageProps) {
  const { id } = await params;

  try {
    const character = await fetchCharacter(Number(id));

    return (
      <div className="max-w-2xl mx-auto space-y-4 animate-fade-in">
        <img
          src={character.image}
          alt={character.name}
          className="w-full object-contain rounded-lg mx-auto shadow-lg"
          style={{ maxHeight: '24rem' }}
        />
        <h1 className="text-3xl font-bold">{character.name}</h1>
        <p>Status: <span className={`badge ${character.status.toLowerCase()}`}>{character.status}</span></p>
        <p>Species: {character.species}</p>
        <p>Gender: {character.gender}</p>
        <p>Origin: {character.origin.name}</p>
        <p>Location: {character.location.name}</p>
        <div>
          <h2 className="text-xl font-semibold">Episodes:</h2>
          <ul className="list-disc pl-5">
            {character.episode.map((ep, i) => (
              <li key={i}>{ep}</li>
            ))}
          </ul>
        </div>
      </div>
    );
  } catch (error) {
    return <ErrorMessage message="Character not found" />;
  }
}

export async function generateStaticParams() {
  // Fetch first page of characters to get initial IDs
  const response = await fetch('https://rickandmortyapi.com/api/character');
  const data = await response.json();

  const totalCharacters = data.info.count;
  const maxCharactersToPrebuild = 20;
  const ids = Array.from(
    { length: Math.min(maxCharactersToPrebuild, totalCharacters) },
    (_, i) => i + 1
  );

  return ids.map((id) => ({
    id: id.toString(),
  }));
}

export const dynamicParams = true; // Allow dynamic params not generated by generateStaticParams